---
openapi: 3.0.3
info:
  title: Application Endpoints Registration
  version: wip
  x-camara-commonalities: 0.6
  description: |
    The Application Endpoints Registration API provides a programmable
    interface for developers to register the endpoints of an application
    which is deployed across various Edge Cloud Zones.
    It allows developers to retrieve, update, and delete those registrations.

    # Introduction

    The API registers the Edge Application Endpoints.
    This information can be used for various use cases like optimal endpoint
    discovery to help end users connect to the most optimal instance of the
    application which is distributed across various Edge Cloud Zones.
    Additionally the information can be used to monitor the edge instances to
    take decisions from a lifecycle management perspective. The API provides
    the ability to register, read and manage the deployed edge instances of
    the application.

    # Relevant terms and definitions

    * **Application Endpoint**:

    The Endpoint on which the application is accessible.
    It can be a URI, FQDN, IPv4, or IPv6 address with a port number.

    # API functionality

    The API provides the following operations:
    - POST registerApplicationEndpoints: Registers the Application Endpoints
                    of a deployed application to a specified edge cloud zone.
    - GET getAllRegisteredApplicationEndpoints: Returns endpoint information for
      all registered Applications.
    - GET getApplicationEndpointsByID: Returns endpoint information for all
        Applications registered to a specified applicationEndpointId.
    - PUT updateApplicationEndpoint: Update registered application endpoint
        information.
    - DELETE deregisterApplicationEndpoint: Deregister an application's
                          application Endpoint from the edge cloud zone.

    # Authorization and authentication

    The "Camara Security and Interoperability Profile" provides details on
    how a client requests an access token. Please refer to Identify and
    Consent Management
    (https://github.com/camaraproject/IdentityAndConsentManagement/)
    for the released version of the Profile.

    Which specific authorization flows are to be used will be determined
    during onboarding process, happening between the API Client and the
    Telco Operator exposing the API, taking into account the declared
    purpose for accessing the API, while also being subject to the prevailing
     legal framework dictated by local legislation.

    It is important to remark that in cases where personal user data
    is processed by the API, and users can exercise their rights through
    mechanisms such as opt-in and/or opt-out, the use of 3-legged access
    tokens becomes mandatory. This measure ensures that the API remains in
    strict compliance with user privacy preferences and regulatory obligations,
    upholding the principles of transparency and user-centric data control.

    # Further info and support

    [GSMA Mobile Connect Account Takeover Protection specification]
    (https://www.gsma.com/identity/wp-content/uploads/2022/12/IDY.24-Mobile-
    Connect-Account-Takeover-Protection-Definition-and-Technical-Requirements-
    v2.0.pdf)
    was used as source of input for this API. For more about Mobile Connect,
    please see [Mobile Connect website](https://mobileconnect.io/).

    (FAQs will be added in a later version of the documentation)

  contact:
    email: sp-edc@lists.camaraproject.org
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
externalDocs:
  description: Project documentation at Camara
  url: https://github.com/camaraproject/EdgeCloud

servers:
  - url: "{apiRoot}/application-endpoint-registration/vwip"
    variables:
      apiRoot:
        default: http://localhost:9091
        description: |
          API root, defined by service provider, e.g.
          `api.example.com` or `api.example.com/somepath`

tags:
  - name: Application Endpoint Registration
    description: |
      Operations to register, read and manage deployed instances of the
      application.

paths:
  /application-endpoints:
    post:
      security:
        - openId:
            - application-endpoint-registration:application-endpoints:write
      tags:
        - Application Endpoint Registration
      summary: Register endpoints of a deployed application
      description: |
        Register the endpoints of a deployed application
        to a specified edge cloud zone.
      operationId: registerApplicationEndpoints
      parameters:
        - $ref: "#/components/parameters/x-correlator"
      requestBody:
        description: Array of Application Endpoints for a
          deployed application
        required: true
        content:
          application/json:
            schema:
              type: array
              minItems: 1
              items:
                $ref: "#/components/schemas/ApplicationEndpointInfo"
      responses:
        "200":
          description: Returns an applicationEndpointsId
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApplicationEndpointsId"
        "400":
          $ref: "#/components/responses/Generic400"
        "401":
          $ref: "#/components/responses/Generic401"
        "403":
          $ref: "#/components/responses/Generic403"
        "404":
          $ref: "#/components/responses/Generic404"
        "405":
          $ref: "#/components/responses/Generic405"
        "422":
          $ref: "#/components/responses/Generic422"
        "429":
          $ref: "#/components/responses/Generic429"
        "500":
          $ref: "#/components/responses/Generic500"
        "501":
          $ref: "#/components/responses/Generic501"
        "502":
          $ref: "#/components/responses/Generic502"
        "503":
          $ref: "#/components/responses/Generic503"
        "504":
          $ref: "#/components/responses/Generic504"
    get:
      security:
        - openId:
            - application-endpoint-registration:application-endpoints:read
      tags:
        - Application Endpoint Registration
      summary: Get all registered edge application endpoint information
      description: |
        Returns endpoint information for all
        Application Endpoints registered.
      operationId: getAllRegisteredApplicationEndpoints
      parameters:
        - $ref: "#/components/parameters/x-correlator"
      responses:
        "200":
          description: Array of registered Application Endpoints
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApplicationEndpoints"
        "400":
          $ref: "#/components/responses/Generic400"
        "401":
          $ref: "#/components/responses/Generic401"
        "403":
          $ref: "#/components/responses/Generic403"
        "404":
          $ref: "#/components/responses/Generic404"
        "405":
          $ref: "#/components/responses/Generic405"
        "422":
          $ref: "#/components/responses/Generic422"
        "429":
          $ref: "#/components/responses/Generic429"
        "500":
          $ref: "#/components/responses/Generic500"
        "501":
          $ref: "#/components/responses/Generic501"
        "502":
          $ref: "#/components/responses/Generic502"
        "503":
          $ref: "#/components/responses/Generic503"
        "504":
          $ref: "#/components/responses/Generic504"

  "/application-endpoints/{applicationEndpointsId}":
    parameters:
      - name: applicationEndpointsId
        in: path
        required: true
        description: The unique identifier for the application endpoints
        schema:
          $ref: "#/components/schemas/ApplicationEndpointsId"
      - $ref: "#/components/parameters/x-correlator"
    get:
      security:
        - openId:
            - application-endpoint-registration:application-endpoints:read
      tags:
        - Application Endpoint Registration
      summary: Get registered edge application endpoint information
      description: |
        Returns endpoint information for all
        Application Endpoints registered to a
        specified applicationEndpointId.
      operationId: getApplicationEndpointsById
      responses:
        "200":
          description: Array of registered Application Endpoints
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApplicationEndpoints"
        "400":
          $ref: "#/components/responses/Generic400"
        "401":
          $ref: "#/components/responses/Generic401"
        "403":
          $ref: "#/components/responses/Generic403"
        "404":
          $ref: "#/components/responses/Generic404"
        "405":
          $ref: "#/components/responses/Generic405"
        "422":
          $ref: "#/components/responses/Generic422"
        "429":
          $ref: "#/components/responses/Generic429"
        "500":
          $ref: "#/components/responses/Generic500"
        "501":
          $ref: "#/components/responses/Generic501"
        "502":
          $ref: "#/components/responses/Generic502"
        "503":
          $ref: "#/components/responses/Generic503"
        "504":
          $ref: "#/components/responses/Generic504"

    put:
      security:
        - openId:
            - application-endpoint-registration:application-endpoints:update
      tags:
        - Application Endpoint Registration
      summary: Update an application Endpoint
      description: |
        Update registered application Endpoint information.
      operationId: updateApplicationEndpoint
      requestBody:
        description: Application Endpoint information
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/ApplicationEndpointInfo"
      responses:
        "204":
          description: Updates Application Endpoint Information
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
        "400":
          $ref: "#/components/responses/Generic400"
        "401":
          $ref: "#/components/responses/Generic401"
        "403":
          $ref: "#/components/responses/Generic403"
        "404":
          $ref: "#/components/responses/Generic404"
        "405":
          $ref: "#/components/responses/Generic405"
        "422":
          $ref: "#/components/responses/Generic422"
        "429":
          $ref: "#/components/responses/Generic429"
        "500":
          $ref: "#/components/responses/Generic500"
        "501":
          $ref: "#/components/responses/Generic501"
        "502":
          $ref: "#/components/responses/Generic502"
        "503":
          $ref: "#/components/responses/Generic503"
        "504":
          $ref: "#/components/responses/Generic504"

    delete:
      security:
        - openId:
            - application-endpoint-registration:application-endpoints:delete
      tags:
        - Application Endpoint Registration
      summary: Deregister an application Endpoint
      description: |
        Deregister an application's
        Endpoint from the edge cloud zone.
      operationId: deregisterApplicationEndpoint
      responses:
        "200":
          description: Deregister Application Endpoint
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
        "400":
          $ref: "#/components/responses/Generic400"
        "401":
          $ref: "#/components/responses/Generic401"
        "403":
          $ref: "#/components/responses/Generic403"
        "404":
          $ref: "#/components/responses/Generic404"
        "405":
          $ref: "#/components/responses/Generic405"
        "422":
          $ref: "#/components/responses/Generic422"
        "429":
          $ref: "#/components/responses/Generic429"
        "500":
          $ref: "#/components/responses/Generic500"
        "501":
          $ref: "#/components/responses/Generic501"
        "502":
          $ref: "#/components/responses/Generic502"
        "503":
          $ref: "#/components/responses/Generic503"
        "504":
          $ref: "#/components/responses/Generic504"

components:
  securitySchemes:
    openId:
      type: openIdConnect
      description: Common security scheme for all CAMARA APIs
      openIdConnectUrl: https://example.com/.well-known/openid-configuration
  headers:
    x-correlator:
      description: Correlation id for the different services
      schema:
        type: string
        pattern: ^[a-zA-Z0-9-]{0,55}$
  parameters:
    x-correlator:
      name: x-correlator
      in: header
      description: Correlation id for the different services
      schema:
        type: string
        pattern: ^[a-zA-Z0-9-]{0,55}$
        example: "b4333c46-49c0-4f62-80d7-f0ef930f1c46"

  schemas:
    ApplicationEndpointInfo:
      description: Application instance represented
        by the application Endpoint definition
      type: object
      properties:
        applicationEndpoint:
          $ref: "#/components/schemas/ResourcesApplicationEndpoint"
        applicationServerProviderName:
          type: string
          description: Unique ID representing the Edge
            Application Provider
        applicationDescription:
          type: string
          description: Description of the application Endpoint
        applicationProfileId:
          $ref: "#/components/schemas/ApplicationProfileId"
        edgeCloudZoneId:
          $ref: "#/components/schemas/EdgeCloudZoneId"
        edgeCloudZoneName:
          $ref: "#/components/schemas/EdgeCloudZoneName"
        edgeCloudProvider:
          $ref: "#/components/schemas/EdgeCloudProvider"
        edgeCloudRegionId:
          $ref: "#/components/schemas/EdgeCloudRegionName"
      required:
        - applicationEndpoint
        - applicationServerProviderName
        - applicationProfileId
        - edgeCloudZoneId
        - edgeCloudZoneName
        - edgeCloudProvider
        - edgeCloudRegionId
      additionalProperties: false
    ApplicationEndpoints:
      description: |
        List of Application endpoints information
        deployed across various cloud zones.
      properties:
        applicationEndpointsId:
          $ref: "#/components/schemas/ApplicationEndpointsId"
        applicationInstance:
          description: |
            Application Endpoint Information
          type: array
          items:
            $ref: "#/components/schemas/ApplicationEndpointInfo"
          minItems: 0
    ResourcesApplicationEndpoint:
      type: object
      description: Resources of the Application Endpoint
      properties:
        uri:
          type: string
          description: URI of application Endpoint if available
          format: uri
        fqdn:
          type: string
          description: FQDN of application Endpoint if available
        ipv4Address:
          type: string
          description: IPv4 Address of application Endpoint if available
          format: ipv4
          example: "203.0.113.10"
        ipv6Address:
          type: string
          description: IPv6 Address of application Endpoint if available
          format: ipv6
          example: 2001:db8:85a3:8d3:1319:8a2e:370:7344
        port:
          type: integer
          description: |
            Port information of application Endpoint
            if IPv4 or IPv6 is mentioned
      anyOf:
        - required: [fqdn, ipv4Address, port]
        - required: [fqdn, ipv6Address, port]
      example:
        {
          "ipv4Address": "203.0.113.10",
          "port": 59765,
          "fqdn": "app.test.com",
          "uri": "http://app.test.com/v1/test"
        }
      additionalProperties: false
    EdgeCloudZoneId:
      description: |
        Operator-issued UUID for the Edge Cloud Zone.
      type: string
      format: uuid
      additionalProperties: false
    EdgeCloudZoneName:
      description: |
        Edge Cloud Zone Name - the common name for the Edge Cloud Zone.
      type: string
      additionalProperties: false
    EdgeCloudProvider:
      description: |
        The company name of the Edge Cloud Zone provider.
      type: string
      additionalProperties: false
    EdgeCloudRegionName:
      description: |
        region of the Edge Cloud Zone.
      type: string
      additionalProperties: false
    ApplicationEndpointsId:
      description: |
        A system-defined string identifier representing
        one or more registered Application Endpoints.
      type: string
      format: uuid
      readOnly: true
      additionalProperties: false
    ApplicationProfileId:
      description: |
        Unique identifier for a Application Profile
      type: string
      readOnly: false
      additionalProperties: false
    ErrorInfo:
      description: Common schema for errors
      type: object
      required:
        - status
        - code
        - message
      properties:
        status:
          type: integer
          description: HTTP status code returned along with this error response
        code:
          type: string
          description: Code given to this error
        message:
          type: string
          description: Detailed error description
  responses:
    Generic400:
      description: Bad Request
      headers:
        x-correlator:
          $ref: "#/components/headers/x-correlator"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ErrorInfo"
              - type: object
                properties:
                  status:
                    enum:
                      - 400
                  code:
                    enum:
                      - INVALID_ARGUMENT
                      - OUT_OF_RANGE
          examples:
            GENERIC_400_INVALID_ARGUMENT:
              description: Invalid Argument. Generic Syntax Exception
              value:
                status: 400
                code: INVALID_ARGUMENT
                message: Client specified an invalid argument,
                  request body or query param.
            GENERIC_400_OUT_OF_RANGE:
              description: Out of Range. Specific Syntax Exception used when a
                given field has a pre-defined range or a invalid filter
                criteria combination is requested
              value:
                status: 400
                code: OUT_OF_RANGE
                message: Client specified an invalid range.

    Generic401:
      description: Unauthorized
      headers:
        x-correlator:
          $ref: "#/components/headers/x-correlator"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ErrorInfo"
              - type: object
                properties:
                  status:
                    enum:
                      - 401
                  code:
                    enum:
                      - UNAUTHENTICATED
          examples:
            GENERIC_401_UNAUTHENTICATED:
              description: Request cannot be authenticated and a new
                authentication is required
              value:
                status: 401
                code: UNAUTHENTICATED
                message: Request not authenticated due to missing, invalid,
                  or expired credentials. A new authentication is required.

    Generic403:
      description: Forbidden
      headers:
        x-correlator:
          $ref: "#/components/headers/x-correlator"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ErrorInfo"
              - type: object
                properties:
                  status:
                    enum:
                      - 403
                  code:
                    enum:
                      - PERMISSION_DENIED
                      - INVALID_TOKEN_CONTEXT
          examples:
            GENERIC_403_PERMISSION_DENIED:
              description: Permission denied. OAuth2 token access does not have
                the required scope or when the user fails operational security
              value:
                status: 403
                code: PERMISSION_DENIED
                message: Client does not have sufficient permissions
                  to perform this action.
            GENERIC_403_INVALID_TOKEN_CONTEXT:
              description: Reflect some inconsistency between information in
                some field of the API and the related OAuth2 Token
              value:
                status: 403
                code: INVALID_TOKEN_CONTEXT
                message: "{{field}} is not consistent with access token."

    Generic404:
      description: Not found
      headers:
        x-correlator:
          $ref: "#/components/headers/x-correlator"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ErrorInfo"
              - type: object
                properties:
                  status:
                    enum:
                      - 404
                  code:
                    enum:
                      - NOT_FOUND
                      - IDENTIFIER_NOT_FOUND
          examples:
            GENERIC_404_NOT_FOUND:
              description: Resource is not found
              value:
                status: 404
                code: NOT_FOUND
                message: The specified resource is not found.

    Generic405:
      description: Method Not Allowed
      headers:
        x-correlator:
          $ref: "#/components/headers/x-correlator"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ErrorInfo"
              - type: object
                properties:
                  status:
                    enum:
                      - 405
                  code:
                    enum:
                      - METHOD_NOT_ALLOWED
          examples:
            GENERIC_405_METHOD_NOT_ALLOWED:
              description: Invalid HTTP verb used with a given endpoint
              value:
                status: 405
                code: METHOD_NOT_ALLOWED
                message: The requested method is not allowed/supported on the
                  target resource.

    Generic422:
      description: Unprocessable Content
      headers:
        x-correlator:
          $ref: "#/components/headers/x-correlator"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ErrorInfo"
              - type: object
                properties:
                  status:
                    enum:
                      - 422
                  code:
                    enum:
                      - IDENTIFIER_MISMATCH
                      - SERVICE_NOT_APPLICABLE
                      - MISSING_IDENTIFIER
                      - UNSUPPORTED_IDENTIFIER
                      - UNNECESSARY_IDENTIFIER
                      - UNIDENTIFIABLE_APPLICATION_PROFILE
          examples:
            GENERIC_422_SERVICE_NOT_APPLICABLE:
              description: Service not applicable for the provided identifier.
              value:
                status: 422
                code: SERVICE_NOT_APPLICABLE
                message: Service not supported for this applicationProfileId
            UNIDENTIFIABLE_APPLICATION_PROFILE:
              description: |
                The Application Profile is not included in the request
                and the profile information cannot be derived
                from the 3-legged access token
              value:
                status: 422
                code: UNIDENTIFIABLE_APPLICATION_PROFILE
                message: The Application Profile cannot be identified

    Generic429:
      description: Too Many Requests
      headers:
        x-correlator:
          $ref: "#/components/headers/x-correlator"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ErrorInfo"
              - type: object
                properties:
                  status:
                    enum:
                      - 429
                  code:
                    enum:
                      - QUOTA_EXCEEDED
                      - TOO_MANY_REQUESTS
          examples:
            GENERIC_429_QUOTA_EXCEEDED:
              description: Request is rejected due to exceeding a business
                quota limit
              value:
                status: 429
                code: QUOTA_EXCEEDED
                message: Out of resource quota.
            GENERIC_429_TOO_MANY_REQUESTS:
              description: Access to the API has been temporarily blocked due to
                rate or spike arrest limits being reached
              value:
                status: 429
                code: TOO_MANY_REQUESTS
                message: Rate limit reached.

    Generic500:
      description: Internal Server Error
      headers:
        x-correlator:
          $ref: "#/components/headers/x-correlator"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ErrorInfo"
              - type: object
                properties:
                  status:
                    enum:
                      - 500
                  code:
                    enum:
                      - INTERNAL
          examples:
            GENERIC_500_INTERNAL:
              description: Problem in Server side. Regular Server Exception
              value:
                status: 500
                code: INTERNAL
                message: Unknown server error. Typically a server bug.

    Generic501:
      description: Not Implemented
      headers:
        x-correlator:
          $ref: "#/components/headers/x-correlator"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ErrorInfo"
              - type: object
                properties:
                  status:
                    enum:
                      - 501
                  code:
                    enum:
                      - NOT_IMPLEMENTED
          examples:
            GENERIC_501_NOT_IMPLEMENTED:
              description: Service not implemented. The use of this code should
                be avoided as far as possible to get the objective to reach
                aligned implementations
              value:
                status: 501
                code: NOT_IMPLEMENTED
                message: This functionality is not implemented yet.
    Generic502:
      description: Bad Gateway
      headers:
        x-correlator:
          $ref: "#/components/headers/x-correlator"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ErrorInfo"
              - type: object
                properties:
                  status:
                    enum:
                      - 502
                  code:
                    enum:
                      - BAD_GATEWAY
          examples:
            GENERIC_502_BAD_GATEWAY:
              description: Internal routing problem in the Server side that
                blocks to manage the service properly
              value:
                status: 502
                code: BAD_GATEWAY
                message: An upstream internal service cannot be reached.
    Generic503:
      description: Service Unavailable
      headers:
        x-correlator:
          $ref: "#/components/headers/x-correlator"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ErrorInfo"
              - type: object
                properties:
                  status:
                    enum:
                      - 503
                  code:
                    enum:
                      - UNAVAILABLE
          examples:
            GENERIC_503_UNAVAILABLE:
              description: Service is not available. Temporary situation
                usually related to maintenance process in the server side
              value:
                status: 503
                code: UNAVAILABLE
                message: Service Unavailable.

    Generic504:
      description: Gateway Timeout
      headers:
        x-correlator:
          $ref: "#/components/headers/x-correlator"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ErrorInfo"
              - type: object
                properties:
                  status:
                    enum:
                      - 504
                  code:
                    enum:
                      - TIMEOUT
          examples:
            GENERIC_504_TIMEOUT:
              description: API Server Timeout
              value:
                status: 504
                code: TIMEOUT
                message: Request timeout exceeded.

